2021-10-18 14:31:56,389 INFO    MainThread:501 [wandb_setup.py:_flush():69] setting env: {}
2021-10-18 14:31:56,390 INFO    MainThread:501 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'eb6f1b610f9f4bb9f1bd7c8e03173a84ea25a050'}
2021-10-18 14:31:56,390 INFO    MainThread:501 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'eb6f1b610f9f4bb9f1bd7c8e03173a84ea25a050'}
2021-10-18 14:31:56,390 INFO    MainThread:501 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-18 14:31:56,390 INFO    MainThread:501 [wandb_init.py:_log_setup():338] Logging user logs to /home/ml2558/CacheSimulator/src/wandb/run-20211018_143156-1c28yve0/logs/debug.log
2021-10-18 14:31:56,390 INFO    MainThread:501 [wandb_init.py:_log_setup():339] Logging internal logs to /home/ml2558/CacheSimulator/src/wandb/run-20211018_143156-1c28yve0/logs/debug-internal.log
2021-10-18 14:31:56,390 INFO    MainThread:501 [wandb_init.py:init():371] calling init triggers
2021-10-18 14:31:56,390 INFO    MainThread:501 [wandb_init.py:init():378] wandb.init called with sweep_config: {}
config: {'only_check_args': False, 'logtostderr': False, 'test_tmpdir': '/tmp/absl_testing', 'showprefixforinfo': True, 'run_with_pdb': False, 'op_conversion_fallback_to_while_loop': False, 'verbosity': -1, 'stderrthreshold': 'fatal', 'use_cprofile_for_profiling': True, 'alsologtostderr': False, 'profile_file': None, 'test_srcdir': '', 'test_random_seed': 301, 'run_with_profiling': False, 'pdb_post_mortem': False, 'v': -1, 'xml_output_file': '', 'test_randomize_ordering_seed': '', 'log_dir': ''}
2021-10-18 14:31:56,391 INFO    MainThread:501 [wandb_init.py:init():420] starting backend
2021-10-18 14:31:56,391 INFO    MainThread:501 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-18 14:31:56,403 INFO    MainThread:501 [backend.py:ensure_launched():135] starting backend process...
2021-10-18 14:31:56,410 INFO    MainThread:501 [backend.py:ensure_launched():140] started backend process with pid: 520
2021-10-18 14:31:56,410 INFO    MainThread:501 [wandb_init.py:init():425] backend started and connected
2021-10-18 14:31:56,416 INFO    MainThread:501 [wandb_init.py:init():473] updated telemetry
2021-10-18 14:31:56,417 INFO    MainThread:501 [wandb_init.py:init():492] communicating current version
2021-10-18 14:31:57,141 INFO    MainThread:501 [wandb_init.py:init():497] got version response upgrade_message: "wandb version 0.12.4 available, but requires python3.6+, see http://wandb.me/library-eol-python35"

2021-10-18 14:31:57,141 INFO    MainThread:501 [wandb_init.py:init():505] communicating run to backend with 30 second timeout
2021-10-18 14:31:57,335 INFO    MainThread:501 [wandb_init.py:init():530] starting run threads in backend
2021-10-18 14:31:59,085 INFO    MainThread:501 [wandb_run.py:_console_start():1625] atexit reg
2021-10-18 14:31:59,086 INFO    MainThread:501 [wandb_run.py:_redirect():1499] redirect: SettingsConsole.REDIRECT
2021-10-18 14:31:59,087 INFO    MainThread:501 [wandb_run.py:_redirect():1504] Redirecting console.
2021-10-18 14:31:59,088 INFO    MainThread:501 [wandb_run.py:_redirect():1560] Redirects installed.
2021-10-18 14:31:59,088 INFO    MainThread:501 [wandb_init.py:init():555] run started, returning control to user process
2021-10-18 14:31:59,089 INFO    Dummy-12  :501 [wandb_run.py:_atexit_cleanup():1595] got exitcode: 1
2021-10-18 14:31:59,089 INFO    Dummy-12  :501 [wandb_run.py:_restore():1567] restore
2021-10-18 14:32:01,607 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-10-18 14:32:01,858 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 734
}

2021-10-18 14:32:02,347 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 3730
}

2021-10-18 14:32:02,449 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 734
  total_bytes: 3888
}

2021-10-18 14:32:02,552 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3730
  total_bytes: 3888
}

2021-10-18 14:32:02,656 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3888
  total_bytes: 3888
}

2021-10-18 14:32:02,767 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3888
  total_bytes: 3888
}

2021-10-18 14:32:02,873 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3888
  total_bytes: 3888
}

2021-10-18 14:32:03,124 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3888
  total_bytes: 3888
}

2021-10-18 14:32:03,230 INFO    Dummy-12  :501 [wandb_run.py:_wait_for_finish():1717] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3888
  total_bytes: 3888
}

2021-10-18 14:32:04,707 INFO    Dummy-12  :501 [wandb_run.py:_show_files():1939] logging synced files
